### ISSUE TITLE
macros in spec doesn't compile

### ISSUE THREAD

**Issue by zmstone** [ramsay-t/Smother#18]
I had a macro -define(undef, undefined). defined in a header file.
the macro in function bodies interpreted well, but the ones in spec ended up like:
-spec myfunction(... ? 151_35_undef)
in the tmp file.

**Comment by ramsay-t** [comment]
You can pass options to smother:compile("someerl.erl",[preprocess]). which will run the preprocessor before it does the smother analysis. This gives you the MC/DC analysis of the code that actually gets compiled, including details of decisions after they have been modified by macros. Its longer but its more accurate and relevant.

I should document the options, should't I :)

Wrangler doesn't cope with specs so smother strips them out and/or ignores them, so it probably isn't careful about dealing with them in the tmp file.

**Comment by zmstone** [comment]
I was using escriptized smother script.
I noticed the "todo" comment in main/1 header: %% @todo Add support for the preprocess option

**Comment by ramsay-t** [comment]
I don't use escriptize - that was contributed by someone else - so if you have a solution please submit it ;)
